import { Listbox } from '@headlessui/react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faChevronDown } from '@fortawesome/free-solid-svg-icons'
// import Logo from './Logo'

type StepTitleSelectProps = {
    suggestedTitles: string[]
    selectedTitle: string
    setSelectedTitle: (title: string) => void
    onNext: (title: string) => void
}

export default function StepTitleSelect({suggestedTitles, onNext, selectedTitle, setSelectedTitle}: StepTitleSelectProps) {
    
    
    function handleOnChange(e: string): void {
        setSelectedTitle(e)
    }

    function handleOnNext(): void {
        onNext(selectedTitle);
    }

    function handleOnKeyEnter(e: any): void {
        if (e.key === 'Enter') {
            handleOnNext()
        }
    }

    return (
        <>
        <div className='flex w-full'>
            <div className='w-16 mr-8'>
                {/* <Logo/> */}
            </div>
            <div className='flex-1'>
                <p>Select a title generated by our artificial friend</p>
                <div className='flex items-center' onKeyDown={handleOnKeyEnter}>
                    <Listbox value={selectedTitle} onChange={handleOnChange}>
                        <Listbox.Button className="mt-2 mr-4 text-md border border-green-500 p-2 w-full flex justify-between items-center">{selectedTitle}<FontAwesomeIcon className='w-2' icon={faChevronDown}></FontAwesomeIcon></Listbox.Button>
                        <Listbox.Options className="absolute w-full h-full top-0 left-0 bg-gray-900 bg-opacity-90 z-50 p-8">
                            <h2 className='text-xl text-white mb-10'>Select a title</h2>
                            <div className=''></div>
                        {suggestedTitles.map((topic, index) => (
                            <Listbox.Option className="border-b border-green-500 p-4 cursor-pointer text-gray-300 hover:bg-slate-800" value={topic} key={index}>
                                {topic}
                            </Listbox.Option>
                        ))}
                        </Listbox.Options>
                    </Listbox>
                    <button className='text-white bg-green-500 p-2 px-4 rounded-sm' onClick={handleOnNext}>Next</button>
                </div>
            </div>
        </div>
        </>
    )
}